[releases]
title = "MAGIC STRAWBERRY SOUND ─ Releases"
url = "http://www.msbsound.com/releases/"
entrySelector = "figure[class='effect-sadie']"
titleSelector = "h2[class='work-title']"
linkSelector = "div[class='table-cell'] a[class='mask-link']"
imageSelector = "img.attachment-1x1.size-1x1.wp-post-image"
contentSelector = "div[class='table-cell']  p[class='entry-meta']"
waitUntil = "networkidle"
onFail = "stale"